In [35]:
import pandas as pd
import numpy as np
import math as m
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn.datasets import load_iris

In [15]:
digits = load_digits()
kf = KFold(n_splits = 3)

In [4]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(digits.data, digits.target, test_size = 0.2)

In [5]:
def get_score(model,xtrain,xtest,ytrain,ytest):
    model.fit(xtrain,ytrain)
    return model.score(xtest,ytest)
    

In [6]:
get_score(LogisticRegression(),xtrain,xtest,ytrain,ytest)

C:\Users\Guest_User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9805555555555555

In [8]:
get_score(SVC(),xtrain,xtest,ytrain,ytest)

0.9972222222222222

In [9]:
get_score(RandomForestClassifier(),xtrain,xtest,ytrain,ytest)

0.9805555555555555

In [10]:
get_score(linear_model.LinearRegression(),xtrain,xtest,ytrain,ytest)

0.5646232765535457

In [12]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)

In [17]:
scores_l = []
scores_svc = []
scores_rfc = []
scores_lin = []

for train_index, test_index in kf.split(digits.data):
    xtrain,xtest,ytrain,ytest = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(),xtrain,xtest,ytrain,ytest))
    scores_rfc.append(get_score(RandomForestClassifier(),xtrain,xtest,ytrain,ytest))
    scores_svc.append(get_score(SVC(),xtrain,xtest,ytrain,ytest))
    scores_lin.append(get_score(linear_model.LinearRegression(),xtrain,xtest,ytrain,ytest))

C:\Users\Guest_User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Guest_User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-le

In [23]:
scores_l


[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [19]:
scores_lin

[0.5210503111571498, 0.5681424219493623, 0.41943985059688305]

In [20]:
scores_svc

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [26]:
scores_rfc

[0.9348914858096828, 0.9432387312186978, 0.9248747913188647]

In [27]:
from sklearn.model_selection import cross_val_score


In [28]:
cross_val_score(LogisticRegression(), digits.data,digits.target)

C:\Users\Guest_User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Guest_User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-le

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [29]:
cross_val_score(SVC(), digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [33]:
cross_val_score(RandomForestClassifier(n_estimators=100), digits.data,digits.target)

array([0.925     , 0.90277778, 0.95543175, 0.95543175, 0.93036212])

In [34]:
cross_val_score(linear_model.LinearRegression(), digits.data,digits.target)

array([0.48346048, 0.5583603 , 0.57534522, 0.5056632 , 0.40995457])

In [36]:
iris = load_iris()

In [37]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [38]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [40]:
df['target'] = iris.target
df.head()
df['flower_name'] = df.target.apply(lambda x: iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target flower_name  
0       0      setosa  
1       0      setosa  
2       0      setosa  
3       0      setosa  
4       0      setosa

In [41]:
x = df.drop(['target', 'flower_name'], axis = 'columns')
y = df.target

In [46]:
cross_val_score(LogisticRegression(),x,y)

C:\Users\Guest_User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [47]:
cross_val_score(SVC(),x,y)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [48]:
cross_val_score(RandomForestClassifier(),x,y)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [49]:
cross_val_score(linear_model.LinearRegression(),x,y)

array([0.        , 0.85124923, 0.        , 0.76155439, 0.        ])